sudo: false
branches:
  only:
    - master

env:
  global:
    - GH_REPO_NAME: bottleos
    - DOCS_DIR: $TRAVIS_BUILD_DIR/docs
    - DOXYFILE: $DOCS_DIR/Doxyfile
    - GH_REPO_REF: github.com/mayant15/bottleos.git

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x $DOCS_DIR/generate-docs.sh
  - $DOCS_DIR/generate-docs.sh
